## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {
  Inv <- NULL ##set initial inverse to NULL
  ##
  set <- function(userValue = matrix()) {
    x <<- userValue 
    Inv <<- NULL
  }
  get <- function() x
  
  ##inverse variable <- desired value 
  setInverse <- function(invVal) {
    cachedInv <<- invVal 
    return(Inv)
  }
  getInverse  <- function() Inv
  list(set=set, get=get, setInverse=setInverse, getInverse=getInverse)
}

## Solves the cached N x N matrix generated by the function makeCacheMatrix

cacheSolve <- function(x=makeCacheMatrix, ...) {
  calculatedInverse <- x$getInverse() 
  
  ##cached value = matrix
  if(!is.null(calculatedInverse) && is.matrix(calculatedInverse)) { 
    message("We found cached data and saved valuable cpus!!!")
    return(calculatedInverse)
  }
  
  ##get the matrix
  matrixToSolve <- x$get()  
  
  ##solve the matrix or give warnings
  calculatedInverse <- tryCatch({ 
    solve(matrixToSolve)
  }, warning=function(w) {
    message("Not sure what happened")
    message(w)
  }, error=function(e) {
    message("There was an error solving your matrix")
    message(e)
    message("\n")
  })
  
  ## whatever the case, set the value of the inverse (NULL if something went wrong)
  message("Setting the value of inverse to:") 
  x$setInverse(calculatedInverse)
  ##Inverse of 'x'
}
